import { User, Tenant, Role, Permission, FeatureFlag, TenantSettings } from '../../types';

// Comprehensive test seed data that matches what tests expect
export const testSeedData = {
  tenants: [
    {
      id: 'acme-corp',
      name: 'Acme Corporation',
      domain: 'acme.example.com',
      settings: {
        allowSelfRegistration: true,
        requireEmailVerification: false,
        sessionTimeout: 3600000,
        maxConcurrentSessions: 3,
        customBranding: {
          primaryColor: '#007bff',
          secondaryColor: '#6c757d',
        },
      } as TenantSettings,
      isActive: true,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'tech-startup',
      name: 'Tech Startup Inc',
      domain: 'techstartup.example.com',
      settings: {
        allowSelfRegistration: true,
        requireEmailVerification: false,
        sessionTimeout: 3600000,
        maxConcurrentSessions: 3,
        customBranding: {
          primaryColor: '#28a745',
          secondaryColor: '#17a2b8',
        },
      } as TenantSettings,
      isActive: true,
      createdAt: new Date('2024-01-15'),
    },
  ] as Tenant[],

  users: [
    {
      id: 'super-admin-1',
      email: 'superadmin@system.com',
      name: 'Super Admin',
      tenantId: 'system',
      roles: ['super_admin'],
      permissions: [
        'read:users',
        'write:users',
        'delete:users',
        'manage:users',
        'manage:roles',
        'view:analytics',
        'read:analytics',
        'manage:system',
        'manage:tenants',
        'read:own',
        'write:own',
      ],
      isActive: true,
      createdAt: new Date('2024-01-01'),
      lastLoginAt: new Date(),
    },
    {
      id: 'admin-1',
      email: 'admin@acme.com',
      name: 'John Admin',
      tenantId: 'acme-corp',
      roles: ['admin'],
      permissions: [
        'read:users',
        'write:users',
        'delete:users',
        'manage:users',
        'manage:roles',
        'view:analytics',
        'read:analytics',
        'manage:system',
        'read:own',
        'write:own',
      ],
      isActive: true,
      createdAt: new Date('2024-01-01'),
      lastLoginAt: new Date(),
    },
    {
      id: 'user-1',
      email: 'user@acme.com',
      name: 'Jane User',
      tenantId: 'acme-corp',
      roles: ['user'],
      permissions: ['read:own', 'write:own', 'view:analytics', 'read:analytics'],
      isActive: true,
      createdAt: new Date('2024-01-05'),
      lastLoginAt: new Date(),
    },
  ] as User[],

  roles: [
    {
      id: 'super-admin',
      name: 'super_admin',
      displayName: 'Super Administrator',
      permissions: [
        { id: 'read:users', name: 'read:users', resource: 'users', action: 'read' },
        { id: 'write:users', name: 'write:users', resource: 'users', action: 'write' },
        { id: 'delete:users', name: 'delete:users', resource: 'users', action: 'delete' },
        { id: 'manage:users', name: 'manage:users', resource: 'users', action: 'manage' },
        { id: 'manage:roles', name: 'manage:roles', resource: 'roles', action: 'manage' },
        { id: 'view:analytics', name: 'view:analytics', resource: 'analytics', action: 'view' },
        { id: 'read:analytics', name: 'read:analytics', resource: 'analytics', action: 'read' },
        { id: 'manage:system', name: 'manage:system', resource: 'system', action: 'manage' },
        { id: 'manage:tenants', name: 'manage:tenants', resource: 'tenants', action: 'manage' },
        { id: 'read:own', name: 'read:own', resource: 'profile', action: 'read' },
        { id: 'write:own', name: 'write:own', resource: 'profile', action: 'write' },
      ] as Permission[],
      isSystemRole: true,
    },
    {
      id: 'admin',
      name: 'admin',
      displayName: 'Administrator',
      permissions: [
        { id: 'read:users', name: 'read:users', resource: 'users', action: 'read' },
        { id: 'write:users', name: 'write:users', resource: 'users', action: 'write' },
        { id: 'delete:users', name: 'delete:users', resource: 'users', action: 'delete' },
        { id: 'manage:users', name: 'manage:users', resource: 'users', action: 'manage' },
        { id: 'manage:roles', name: 'manage:roles', resource: 'roles', action: 'manage' },
        { id: 'view:analytics', name: 'view:analytics', resource: 'analytics', action: 'view' },
        { id: 'read:analytics', name: 'read:analytics', resource: 'analytics', action: 'read' },
        { id: 'manage:system', name: 'manage:system', resource: 'system', action: 'manage' },
        { id: 'read:own', name: 'read:own', resource: 'profile', action: 'read' },
        { id: 'write:own', name: 'write:own', resource: 'profile', action: 'write' },
      ] as Permission[],
      isSystemRole: true,
    },
    {
      id: 'user',
      name: 'user',
      displayName: 'User',
      permissions: [
        { id: 'read:own', name: 'read:own', resource: 'profile', action: 'read' },
        { id: 'write:own', name: 'write:own', resource: 'profile', action: 'write' },
        { id: 'view:analytics', name: 'view:analytics', resource: 'analytics', action: 'view' },
        { id: 'read:analytics', name: 'read:analytics', resource: 'analytics', action: 'read' },
      ] as Permission[],
      isSystemRole: true,
    },
  ] as Role[],

  featureFlags: {
    'new-dashboard': {
      key: 'new-dashboard',
      name: 'New Dashboard Design',
      description: 'Enable the redesigned dashboard with improved UX',
      category: 'ui',
      serverEnabled: true,
      adminEditable: true,
      defaultState: true,
      rolloutPercentage: 100,
      tenantId: 'acme-corp',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    'premium-analytics': {
      key: 'premium-analytics',
      name: 'Premium Analytics',
      description: 'Advanced analytics and reporting features',
      category: 'feature',
      serverEnabled: true,
      adminEditable: true,
      defaultState: false,
      tenantId: 'acme-corp',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    'beta-features': {
      key: 'beta-features',
      name: 'Beta Features Access',
      description: 'Access to experimental beta features',
      category: 'experiment',
      serverEnabled: true,
      adminEditable: true,
      defaultState: false,
      rolloutPercentage: 25,
      userSegment: ['beta-testers'],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
  } as Record<string, FeatureFlag>,
};
